# Dockerfile

FROM tensorflow/tensorflow:2.3.0

WORKDIR /root

ENV PROJECT_ID=alekseyv-scalableai-dev
ENV GOOGLE_APPLICATION_CREDENTIALS=/root/service_account_key.json
COPY service_account_key.json /root/

RUN pip --version
RUN python --version
RUN pip install nbdev

RUN pip install keras-tuner
RUN pip install --no-deps tensorflow-io==0.15.0

RUN pip install google-cloud
RUN pip install google-cloud-bigquery
RUN pip install matplotlib
RUN pip install pandas
# See https://stackoverflow.com/questions/59187054/runtimeerror-unable-to-create-link-name-already-exists-when-i-append-hdf5-fil
RUN pip uninstall -y h5py
RUN pip install h5py

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

#ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

RUN git clone https://github.com/vlasenkoalexey/gcp_runner
RUN pip install -e gcp_runner

RUN mkdir /root/models
RUN mkdir /root/criteo_nbdev
COPY criteo_nbdev/* /root/criteo_nbdev/