# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['StopExecution', 'skip', 'run_all', 'set_google_application_credentials']

# Cell
run_all = False

class StopExecution(Exception):
    def _render_traceback_(self):
        pass

def skip():
    if not run_all:
        raise StopExecution

# Cell
import os
import os.path
from .constants import *

def set_google_application_credentials():
    os.environ['GOOGLE_APPLICATION_CREDENTIALS']=os.path.join(os.getcwd(), SERVICE_ACCOUNT_KEY_FILE_NAME)
