# AUTOGENERATED! DO NOT EDIT! File to edit: 10_entry_point.ipynb (unless otherwise specified).

__all__ = []

# Cell
import gcp_runner.entry_point

if __name__ == '__main__':
    gcp_runner.entry_point.main()